"""
This file contains the migration for the profile model.
"""

# Generated by Django 4.2.20 on 2025-03-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    This migration adds the resume field to the profile model.
    """
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
