"""
This file contains the migration for the resume model.
"""

# Generated by Django 4.2.20 on 2025-03-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    This migration creates the resume model.
    """

    dependencies = [
        ('users', '0002_profile_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resumes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='resume',
        ),
    ]
