"""
This file contains the migration for the profile model.
"""

# Generated by Django 4.2.20 on 2025-03-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    This migration alters the avatar field of the profile model.
    """

    dependencies = [
        ('users', '0003_resume_remove_profile_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default.jpg', null=True,
                                    upload_to='avatars'),
        ),
    ]
