# Generated by Django 4.2.20 on 2025-03-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='whitelisted_for_ai',
            field=models.BooleanField(default=False),
        ),
    ]
