# Generated by Django 4.2.20 on 2025-03-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_whitelisted_for_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='industry_preference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_preference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='remote_preference',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='salary_min_preference',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
