# Generated by Django 4.2.20 on 2025-03-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_industry_preference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='industry_preference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location_preference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='salary_min_preference',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
