app = 'group-4-spring-2025'
primary_region = 'iad'
swap_size_mb = 512

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[mounts]]
  source = 'group_4_database'
  destination = '/app/database'


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1