# Generated by Django 5.2a1 on 2025-03-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_word', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True)),
                ('type', models.CharField(max_length=100)),
                ('progress', models.CharField(choices=[('U', 'Unfinished'), ('F', 'Finished')], max_length=100)),
            ],
        ),
    ]
