# Generated by Django 4.2.20 on 2025-03-10 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
