# Generated by Django 5.2a1 on 2025-04-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='location',
            field=models.CharField(default='North Pole - Top Secret Underground', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='progress',
            field=models.CharField(default='Searched For', max_length=100),
        ),
    ]
