# Generated by Django 4.2.20 on 2025-04-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_application_location_alter_application_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('company_logo', models.URLField(blank=True, null=True)),
                ('job_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='home_joblis_title_1edd85_idx'), models.Index(fields=['company'], name='home_joblis_company_41bbda_idx'), models.Index(fields=['location'], name='home_joblis_locatio_af20dc_idx'), models.Index(fields=['job_type'], name='home_joblis_job_typ_cadd4f_idx')],
            },
        ),
    ]
