# Generated by Django 4.2.20 on 2025-04-08 03:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_joblisting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joblisting',
            options={'ordering': ['-published_at']},
        ),
        migrations.RemoveIndex(
            model_name='joblisting',
            name='home_joblis_title_1edd85_idx',
        ),
        migrations.RemoveIndex(
            model_name='joblisting',
            name='home_joblis_company_41bbda_idx',
        ),
        migrations.RemoveIndex(
            model_name='joblisting',
            name='home_joblis_locatio_af20dc_idx',
        ),
        migrations.RemoveIndex(
            model_name='joblisting',
            name='home_joblis_job_typ_cadd4f_idx',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='cached_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='search_key',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='company_logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='url',
            field=models.URLField(max_length=500),
        ),
        migrations.AddIndex(
            model_name='joblisting',
            index=models.Index(fields=['search_key', 'cached_at'], name='home_joblis_search__80685b_idx'),
        ),
    ]
