# Generated by Django 4.2.20 on 2025-04-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_joblisting_home_joblis_search__80685b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='job_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='job_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
