# Generated by Django 4.2.20 on 2025-05-02 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_userjobinteraction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
